name: Demo React Application
on: 
  push:
    branches: 
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"      
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Building the image from Dockerfile
        run: docker build -t react-app:latest reach-app/
      - run: echo "Job status is now ${{job.status}}
        
 
